version: '2.4'
#### Services ####
services:
  #### Data-Collector ####
  datacollector:
    build:
      context: ./data-collector
      args: 
        - http_proxy=http://194.145.60.250:9400
        - https_proxy=http://194.145.60.250:9400
    image: data-collector_edge:0.0.1
    container_name: data-collector
    restart: always
    networks:
      - proxy-redirect
    volumes:
      - './publish/:/publish/'
      - './cfg-data/:/cfg-data/'
    mem_limit: 200mb

  #### InfluxDB ####
  influxdb:
    build:
      context: ./influxdb
    image: influxdb_edge:0.0.1
    container_name: influxdb
    restart: always
    networks:
      - proxy-redirect
    ports:
      - "8086:8086"
    mem_limit: 1gb

  #### Grafana ####
  grafana:
    build:
      context: ./grafana
    image: grafana_edge:0.0.1
    container_name: grafana
    restart: always
    networks:
      - proxy-redirect
    ports:
      - "33000:3000"
    mem_limit: 400mb


#### Network ####
networks:
  proxy-redirect:
    name: proxy-redirect 